name: verify/validate & print secret

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Maven validate
      run: mvn validate

    - name: print secret and version
      run: |
        echo "GitHub Secret: ${{ secrets.MY_SECRET }}"
        echo "Project Version: ${{ steps.get_version.outputs.version }}"
